services:
  - type: web
    name: amazonproject
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT AmazonProject.asgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: AmazonProject.settings
