services:
  - type: web
    name: amazonproject
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn AmazonProject.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: AmazonProject.settings
